build-id-var: CUSTOM_BUILD_NUM
tag-suffix: -t{{BuildID}}
template-vars:
  CURRENT_GO_VERSION: 1.9.2
  PREVIOUS_GO_VERSION: 1.8.3
  CURRENT_GO_SRC_SHA256: 665f184bf8ac89986cfd5a4460736976f60b57df6b320ad71ad4cef53bb143dc
  CURRENT_GO_LINUX_AMD64_SHA256: de874549d9a8d8d8062be05808509c09a88a248e77ec14eb77453530829ac02b
  PREVIOUS_GO_SRC_SHA256: 5f5dea2447e7dcfdc50fa6b94c512e58bfba5673c039259fd843f68829d99fa6
  PREVIOUS_GO_LINUX_AMD64_SHA256: 1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772
  GODEL_VERSION: 0.21.0
  GO_1_9_VERSION: 1.9.2
  GO_1_8_VERSION: 1.8.3
  DOCKER_VERSION: 17.03.0-ce
builds:
  alpine-go:
    docker-template: alpine-go-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_VERSION}}
    for:
      GO_VERSION:
        - "{{.GO_1_9_VERSION}}"
        - "{{.GO_1_8_VERSION}}"
  brew-go:
    docker-template: brew-go/Dockerfile_template.txt
    tag: nmiyake/go:brew-go
  go-darwin-linux:
    docker-template: go-darwin-linux/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-docker-bsdtar-unzip:
    docker-template: go-darwin-linux-docker-bsdtar-unzip/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-bsdtar-unzip
    requires:
      - go-darwin-linux
  go-darwin-linux-docker-java-ruby-netcat:
    docker-template: go-darwin-linux-docker-java-ruby-netcat/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-java-ruby-netcat
    requires:
      - go-darwin-linux
  go-darwin-linux-no-cgo:
    docker-template: go-darwin-linux-no-cgo/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-no-cgo-docker-rpm-fpm:
    docker-template: go-darwin-linux-no-cgo-docker-rpm-fpm-template/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-rpm-fpm
    requires:
      - go-darwin-linux-no-cgo
  go-docker:
    docker-template: go-docker-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}
