build-id-var: CUSTOM_BUILD_NUM
tag-suffix: -t{{BuildID}}
template-vars:
  CURRENT_GO_VERSION: 1.11.3
  PREVIOUS_GO_VERSION: 1.10.6
  CURRENT_GO_SRC_SHA256: 7ec5140f384db2bd42b396c93c231dfba342ee137ad8a4b33120016951eb1231
  CURRENT_GO_LINUX_AMD64_SHA256: d20a4869ffb13cee0f7ee777bf18c7b9b67ef0375f93fac1298519e0c227a07f
  PREVIOUS_GO_SRC_SHA256: 0f6bd961f6d2d6fa6319b7dc9548e2ae22d0698e7432d4cabf737542913f8c14
  PREVIOUS_GO_LINUX_AMD64_SHA256: acbdedf28b55b38d2db6f06209a25a869a36d31bdcf09fd2ec3d40e1279e0592
  GODEL_VERSION: 1.3.0
  GO_1_10_VERSION: 1.10.6
  GO_1_9_VERSION: 1.9.7
  DOCKER_VERSION: 17.06.0-ce
builds:
  alpine-go:
    docker-template: alpine-go-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_VERSION}}
    for:
      GO_VERSION:
        - "{{.CURRENT_GO_VERSION}}"
        - "{{.PREVIOUS_GO_VERSION}}"
  alpine-go-java-8u181:
    docker-template: alpine-go-java-8u181-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.CURRENT_GO_VERSION}}-java-8u181
    requires:
      - alpine-go
  brew-go:
    docker-template: brew-go/Dockerfile_template.txt
    tag: nmiyake/go:brew-go
  go-darwin-linux:
    docker-template: go-darwin-linux/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-no-cgo:
    docker-template: go-darwin-linux-no-cgo/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-no-cgo-java-8u181:
    docker-template: go-darwin-linux-no-cgo-java-8u181/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}-java-8u181
    requires:
      - go-darwin-linux-no-cgo
  go-darwin-linux-no-cgo-java-11:
    docker-template: go-darwin-linux-no-cgo-java-11/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}-java-11
    requires:
      - go-darwin-linux-no-cgo
  go-docker:
    docker-template: go-docker-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}
