build-id-var: CUSTOM_BUILD_NUM
tag-suffix: -t{{BuildID}}
template-vars:
  CURRENT_GO_VERSION: 1.9
  PREVIOUS_GO_VERSION: 1.8.3
  CURRENT_GO_SRC_SHA256: a4ab229028ed167ba1986825751463605264e44868362ca8e7accc8be057e993
  CURRENT_GO_LINUX_AMD64_SHA256: d70eadefce8e160638a9a6db97f7192d8463069ab33138893ad3bf31b0650a79
  PREVIOUS_GO_SRC_SHA256: 5f5dea2447e7dcfdc50fa6b94c512e58bfba5673c039259fd843f68829d99fa6
  PREVIOUS_GO_LINUX_AMD64_SHA256: 1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772
  GODEL_VERSION: 0.21.0
  GO_1_9_VERSION: 1.9
  GO_1_8_VERSION: 1.8.3
  DOCKER_VERSION: 17.03.0-ce
builds:
  alpine-go:
    docker-template: alpine-go-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_VERSION}}
    for:
      GO_VERSION:
        - "{{.GO_1_9_VERSION}}"
        - "{{.GO_1_8_VERSION}}"
  alpine-go-curr-prev:
    docker-template: alpine-go-curr-prev-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_1_9_VERSION}}-{{.GO_1_8_VERSION}}
  brew-go:
    docker-template: brew-go/Dockerfile_template.txt
    tag: nmiyake/go:brew-go
  go-curr-prev:
    docker-template: go-curr-prev-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.GO_1_9_VERSION}}-{{.GO_1_8_VERSION}}
  go-darwin-linux:
    docker-template: go-darwin-linux/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-docker-rpm-fpm:
    docker-template: go-darwin-linux-docker-rpm-fpm-template/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-rpm-fpm
  go-darwin-linux-no-cgo:
    docker-template: go-darwin-linux-no-cgo/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}
  go-docker:
    docker-template: go-docker-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}
  go-godel:
    docker-template: go-godel/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}-godel-{{.GODEL_VERSION}}
