build-id-var: CUSTOM_BUILD_NUM
tag-suffix: -t{{BuildID}}
template-vars:
  CURRENT_GO_VERSION: 1.11.2
  PREVIOUS_GO_VERSION: 1.10.5
  CURRENT_GO_SRC_SHA256: 042fba357210816160341f1002440550e952eb12678f7c9e7e9d389437942550
  CURRENT_GO_LINUX_AMD64_SHA256: 1cb34dffecb3c3d441667954bab5b7fdb048c40704b76cd801f09796b909ff50
  PREVIOUS_GO_SRC_SHA256: f0a3ed5c775f39a970d4937c64b3b178992e23a5df57ae56a59a1c99253094f4
  PREVIOUS_GO_LINUX_AMD64_SHA256: a035d9beda8341b645d3f45a1b620cf2d8fb0c5eb409be36b389c0fd384ecc3a
  GODEL_VERSION: 1.3.0
  GO_1_10_VERSION: 1.10.5
  GO_1_9_VERSION: 1.9.7
  DOCKER_VERSION: 17.06.0-ce
builds:
  alpine-go:
    docker-template: alpine-go-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_VERSION}}
    for:
      GO_VERSION:
        - "{{.CURRENT_GO_VERSION}}"
        - "{{.PREVIOUS_GO_VERSION}}"
  alpine-go-java-8u181:
    docker-template: alpine-go-java-8u181-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.CURRENT_GO_VERSION}}-java-8u181
    requires:
      - alpine-go
  brew-go:
    docker-template: brew-go/Dockerfile_template.txt
    tag: nmiyake/go:brew-go
  go-darwin-linux:
    docker-template: go-darwin-linux/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-docker-bsdtar-unzip:
    docker-template: go-darwin-linux-docker-bsdtar-unzip/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-bsdtar-unzip
    requires:
      - go-darwin-linux
  go-darwin-linux-docker-java-ruby-netcat:
    docker-template: go-darwin-linux-docker-java-ruby-netcat/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-java-ruby-netcat
    requires:
      - go-darwin-linux
  go-darwin-linux-no-cgo:
    docker-template: go-darwin-linux-no-cgo/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}
  go-darwin-linux-no-cgo-java-8u181:
    docker-template: go-darwin-linux-no-cgo-java-8u181/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}-java-8u181
  go-darwin-linux-no-cgo-docker-rpm-fpm:
    docker-template: go-darwin-linux-no-cgo-docker-rpm-fpm-template/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-no-cgo-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}-rpm-fpm
    requires:
      - go-darwin-linux-no-cgo
  go-docker:
    docker-template: go-docker-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}
