build-id-var: CIRCLE_BUILD_NUM
tag-suffix: -t{{BuildID}}
template-vars:
  CURRENT_GO_VERSION: 1.8.3
  GO_1_8_VERSION: 1.8.3
  GO_1_7_VERSION: 1.7.6
  GO_1_6_VERSION: 1.6.4
  DOCKER_VERSION: 17.03.0-ce
  GO_1_8_SRC_SHA256: 5f5dea2447e7dcfdc50fa6b94c512e58bfba5673c039259fd843f68829d99fa6
  GO_1_8_LINUX_AMD64_SHA256: 1862f4c3d3907e59b04a757cfda0ea7aa9ef39274af99a784f5be843c80c6772
  GO_1_7_SRC_SHA256: 1a67a4e688673fdff7ba41e73482b0e59ac5bd0f7acf703bc6d50cc775c5baba
  GO_1_7_LINUX_AMD64_SHA256: ad5808bf42b014c22dd7646458f631385003049ded0bb6af2efc7f1f79fa29ea
builds:
  alpine-go-1.7-1.8:
    docker-template: alpine-go-1.7-1.8-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_1_7_VERSION}}-{{.GO_1_8_VERSION}}
  alpine-go:
    docker-template: alpine-go-template/Dockerfile_template.txt
    tag: nmiyake/go:alpine-go-{{.GO_VERSION}}
    for:
      GO_VERSION:
        - "{{.GO_1_8_VERSION}}"
        - "{{.GO_1_7_VERSION}}"
        - "{{.GO_1_6_VERSION}}"
  brew-go:
    docker-template: brew-go/Dockerfile_template.txt
    tag: nmiyake/go:brew-go
  go-1.7-1.8:
    docker-template: go-1.7-1.8-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.GO_1_7_VERSION}}-{{.GO_1_8_VERSION}}
  go-darwin-linux:
    docker-template: go-darwin-linux/Dockerfile_template.txt
    tag: nmiyake/go:go-darwin-linux-{{.GO_1_8_VERSION}}
  go-docker:
    docker-template: go-docker-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.CURRENT_GO_VERSION}}-docker-{{.DOCKER_VERSION}}
  go-rpm-fpm:
    docker-template: go-rpm-fpm-template/Dockerfile_template.txt
    tag: nmiyake/go:go-{{.CURRENT_GO_VERSION}}-rpm-fpm
