defaults: &defaults
  working_directory: /go/src/github.com/nmiyake/go-docker-images
  docker:
    - image: nmiyake/go:go-1.8.3-docker-17.03.0-ce-t52

custom-build-num: &custom-build-num
  run: echo "export CUSTOM_BUILD_NUM=$(($(git rev-list --count HEAD)+80))" >> $BASH_ENV

run-docker-gen: &run-docker-gen
  run: go run ./vendor/github.com/nmiyake/dockergen/main.go --config config.yml build $IMAGE

docker-save: &docker-save
  run: |
       mkdir -p /tmp/docker-cache
       docker save -o /tmp/docker-cache/docker-images.tar $(go run ./vendor/github.com/nmiyake/dockergen/main.go --config config.yml tags $IMAGE)

create-cache-key: &create-cache-key
  run: echo "$IMAGE-$CIRCLE_SHA1" > /tmp/$IMAGE-cache_key.txt

docker-load: &docker-load
  run: docker load -i /tmp/docker-cache/docker-images.tar

docker-publish: &docker-publish
  run: |
       docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
       go run ./vendor/github.com/nmiyake/dockergen/main.go --config config.yml push $IMAGE

version: 2
jobs:
  alpine-go:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=alpine-go' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/alpine-go-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  alpine-go-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=alpine-go' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/alpine-go-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  alpine-go-curr-prev:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=alpine-go-curr-prev' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/alpine-go-curr-prev-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  alpine-go-curr-prev-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=alpine-go-curr-prev' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/alpine-go-curr-prev-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  brew-go:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=brew-go' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/brew-go-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  brew-go-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=brew-go' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/brew-go-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  go-curr-prev:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-curr-prev' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/go-curr-prev-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  go-curr-prev-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-curr-prev' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/go-curr-prev-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  go-darwin-linux:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-darwin-linux' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/go-darwin-linux-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  go-darwin-linux-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-darwin-linux' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/go-darwin-linux-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  go-darwin-linux-docker-rpm-fpm:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-darwin-linux-docker-rpm-fpm' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/go-darwin-linux-docker-rpm-fpm-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  go-darwin-linux-docker-rpm-fpm-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-darwin-linux-docker-rpm-fpm' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/go-darwin-linux-docker-rpm-fpm-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  go-darwin-linux-no-cgo:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-darwin-linux-no-cgo' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/go-darwin-linux-no-cgo-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  go-darwin-linux-no-cgo-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-darwin-linux-no-cgo' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/go-darwin-linux-no-cgo-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  go-docker:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-docker' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/go-docker-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  go-docker-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-docker' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/go-docker-cache_key.txt" }}
      - *docker-load
      - *docker-publish

  go-godel:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-godel' >> $BASH_ENV
      - *custom-build-num
      - *run-docker-gen
      - *docker-save
      - *create-cache-key
      - save_cache:
          key: docker-image-{{ checksum "/tmp/go-godel-cache_key.txt" }}
          paths:
            - /tmp/docker-cache/docker-images.tar
  go-godel-publish:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: echo 'export IMAGE=go-godel' >> $BASH_ENV
      - *custom-build-num
      - *create-cache-key
      - restore_cache:
          keys:
            - docker-image-{{ checksum "/tmp/go-godel-cache_key.txt" }}
      - *docker-load
      - *docker-publish

workflows:
  version: 2
  build-publish:
    jobs:
      - alpine-go
      - alpine-go-publish:
          requires:
            - alpine-go
          filters:
            branches:
              only: /^master$/

      - alpine-go-curr-prev
      - alpine-go-curr-prev-publish:
          requires:
            - alpine-go-curr-prev
          filters:
            branches:
              only: /^master$/

      - brew-go
      - brew-go-publish:
          requires:
            - brew-go
          filters:
            branches:
              only: /^master$/

      - go-curr-prev
      - go-curr-prev-publish:
          requires:
            - go-curr-prev
          filters:
            branches:
              only: /^master$/

      - go-darwin-linux
      - go-darwin-linux-publish:
          requires:
            - go-darwin-linux
          filters:
            branches:
              only: /^master$/

      - go-darwin-linux-docker-rpm-fpm
      - go-darwin-linux-docker-rpm-fpm-publish:
          requires:
            - go-darwin-linux-docker-rpm-fpm
          filters:
            branches:
              only: /^master$/

      - go-darwin-linux-no-cgo
      - go-darwin-linux-no-cgo-publish:
          requires:
            - go-darwin-linux-no-cgo
          filters:
            branches:
              only: /^master$/

      - go-docker
      - go-docker-publish:
          requires:
            - go-docker
          filters:
            branches:
              only: /^master$/

      - go-godel
      - go-godel-publish:
          requires:
            - go-godel
          filters:
            branches:
              only: /^master$/
